project:
  type: website

website:
  title: "plotting"
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/neilstats
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto
